### PR TITLE
Add an OgmiosV6 backend based on ogmios-python

### PR DESCRIPTION
**Pull request by nielstron**
This requires bumping the python version to 3.10+, because ogmios-python requires this. I also refactored the chain backend to not have built-in kupo support but just provide it as an extension using kupo-wrappers. This way, both OgmiosV5 and OgmiosV6 directly have support for kupo.

### CODE REVIEW

**Comment by nielstron** [comment]
This error occurs in mypy, not sure where it comes from
```
error: --install-types failed (no mypy cache directory)
```

**Comment by cffls** [comment]
Wow nice! Thanks a lot for adding this support. Will take a look at the error. 
Regarding the min version bump, is it because of the dependency on `ogmios = "^1.1.1"`?

**Comment by nielstron** [comment]
Yes unfortunately Ogmios does not support python 3.8 and 3.9

**Comment by cffls** [comment]
I had to bump the [python version of mypy](https://github.com/Python-Cardano/pycardano/pull/368/files#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711R80) to "3.10" for this to run. 

Here are few errors:

```
pycardano/backend/kupo.py:186: error: "KupoChainContextExtension" has no attribute "_extract_asset_info"  [attr-defined]
pycardano/backend/ogmios_v6.py:152: error: Argument "decentralization_param" to "ProtocolParameters" has incompatible type "None"; expected "Fraction"  [arg-type]
pycardano/backend/ogmios_v6.py:156: error: Argument "min_utxo" to "ProtocolParameters" has incompatible type "None"; expected "int"  [arg-type]
pycardano/backend/ogmios_v6.py:359: error: Argument 2 to "OgmiosV6ChainContext" has incompatible type "Network"; expected "int"  [arg-type]
Found 4 errors in 2 files (checked 31 source files)
make: *** [qa] Error 1
```

**Comment by pcjordan** [comment]
fyi, I tried to work with this branch and here's another error I encountered: 

File ".../pycardano/backend/ogmios_v6.py", line 288, in _utxo_from_ogmios_result
    Address.from_primitive(utxo.address),
AttributeError: type object 'Address' has no attribute 'from_primitive'

I guess in (at least) the following two places the pycardano.Address should be used instead of ogmios.datatypes.Address:
https://github.com/Python-Cardano/pycardano/blob/0e285e5bfcb85e56d29cea5202fc910f94a59303/pycardano/backend/ogmios_v6.py#L272
https://github.com/Python-Cardano/pycardano/blob/0e285e5bfcb85e56d29cea5202fc910f94a59303/pycardano/backend/ogmios_v6.py#L288

**Comment by nielstron** [comment]
Did anyone of you @pcjordan or @cffls encounter/resolve the weird mypy error in the CI?

**Comment by nielstron** [comment]
Thanks for your support @cffls @pcjordan. Filed some issue at python-ogmios to achieve full 3.8/3.9 support again and then lets see about the unit tests (should ideally also add some unit tests for ogmios v6 and documentation here, maybe @cffls can help me out there?)

**Comment by wrmarchetto** [comment]
When this is ready to merge, I'll release the compatible version of ogmios-python (currently in the `main` branch).

**Comment by nielstron** [comment]
Thanks @wrmarchetto !

**Comment by cffls** [comment]
Thanks for fixing issues! FYI, I merged this branch (`feat/add_v6_backend`) to [chang](https://github.com/Python-Cardano/pycardano/tree/chang), and all tests are passing. I think it might be a good idea to push changes to chang branch going forward. wdyt?

**Comment by nielstron** [comment]
Sounds good.

**Pull request closed without merging**
