### PR TITLE
Add transaction builder with metadata example

### PR DESCRIPTION
**Pull request by B3nac**
Hi! I created an example today and thought I'd share. Awesome library, I'm having so much fun with it!

P.S. the discord invite is invalid, please update. Cheers! :beers:

### CODE REVIEW

**Comment by nielstron** [comment]
Thanks for submitting this PR!

Could you add a comment about which CIP this transaction metadata is for? Or alternatively make it match the format of some CIP so users can see how to map between CIP specifications and PyCardano Metadata :)

Also which discord link do you mean? I clicked on the badge in the readme and it was still valid.

**Comment by B3nac** [comment]
Yeah for sure! I'll work on it at lunch. Turns out Brave shields were blocking the Discord invite :laughing:.

**Review by nielstron — APPROVED** [review]
Looks good to me, thank you very much!

**Comment by cffls** [comment]
Thanks for your contribution @B3nac ! There is one minor issue in the format checker. You can reformat the code with `make format` and verify it with `make qa`.

**Comment by B3nac** [comment]
No problem @nielstron @cffls! That should do the trick. :beers:

**Pull request merged**
