### PR TITLE
implement no type checking flag

### LINKED ISSUE #229: Make typeguard toggleable to increase speed
**Is your feature request related to a problem? Please describe.**
Although typeguard is useful when initial debugging, it can slow down heavy use of pycardano. When I remove typeguard, I get almost 2x increase in speed. I would like there to be an option to turn off typegaurd type checking.

**Describe the solution you'd like**
Create a flag or environment variable that turns off typeguard.

**Describe alternatives you've considered**
N/A

**Additional context**
I'm trying to increase the speed of my hypothesis tests: https://github.com/OpShin/opshin-pioneer-program/pull/43

### PR DESCRIPTION
**Pull request by juliusfrost**
Resolves #229

### CODE REVIEW

**Comment by juliusfrost** [comment]
@cffls ready for your review :)

**Comment by cffls** [comment]
Thanks @juliusfrost for creating this feature. In fact, typeguard provides a native solution for [typecheck suppression](https://typeguard.readthedocs.io/en/latest/userguide.html#suppressing-type-checks). Do you think the native solution from typeguard is sufficient?

**Comment by juliusfrost** [comment]
Hi @cffls, I tried your suggestion but I couldn't get it to work (it doesn't suppress subsequent calls to methods). For my use case, I need to disable it globally for my tests. I found that if you use PYTHONOPTIMIZE it does disable the checks, but also disables assertions so I can't use with my tests since they need assertions.

**Comment by cffls** [comment]
Thanks for trying it out. Not sure why it didn't work. I will merge this PR since it is proven to be working. :D

**Review by cffls — APPROVED** [review]

**Comment by juliusfrost** [comment]
Thanks!

**Pull request merged**
