### PR TITLE
Correctly parse List[X] annotated objects

### PR DESCRIPTION
**Pull request by nielstron**
Imperatorlang allows users to specify PlutusData like this

```
@dataclass()
class D(PlutusData):
  xs: List[A]  # where A is also PlutusData
```

This was previously not correctly parsed by Pycardano. I suggest the List notation is also added to the main Pycardano, as it otherwise lacks the ability to build complex objects.

### CODE REVIEW

**Comment by cffls** [comment]
Thanks! The change makes sense. Could you add a test for it? LGTM otherwise.

**Comment by nielstron** [comment]
Future todos (for another PR)
- implement the same for Dict -> #180 
- ~~fix the case where CBORTags are > 7 (this is covered by the plutus implementation but not widely documented)~~

**Comment by nielstron** [comment]
@cffls Please review

**Comment by nielstron** [comment]
Again, coverage submission failed :/

**Review by cffls — APPROVED** [review]

**Pull request merged**
