### PR TITLE
Fix: negative minted amount is also requested

### PR DESCRIPTION
**Pull request by nielstron**
For transactions that only specified a token to be burned it could currently happen that the token was not selected by the input selector - because negative minting amounts were not counted as requested by the tx builder. This is a bugfix.

- [x] Add a unit test

### CODE REVIEW

**Comment by MuesliSwapTeam** [comment]
The only error appears to have been uploading to Codecov

**Comment by nielstron** [comment]
The only error appears to have been uploading to Codecov

**Comment by nielstron** [comment]
Note: this breaks if the burned amount is manually added as input, because the minted amount is added to the `selected_amount`, resulting in `0`. This is valid as the amount can not be used anymore later. However modeling it as a requested output leverages the coinselection to automatically fetch the required input for the burning.

**Comment by cffls** [comment]
Nice! I will try to add a test. Btw, is there a way to allow me to push to your branch ([OpShin:fix/minted_amount_requested](https://github.com/OpShin/pycardano/tree/fix/minted_amount_requested))?

**Comment by nielstron** [comment]
You should have access now :)

**Comment by nielstron** [comment]
I fixed the previously mentioned issue when pre-selected inputs contain the token to be burned. What's missing is a unit test that checks the automatic selection of tokens to be burned

**Review by cffls — APPROVED** [review]

**Pull request merged**
