### PR TITLE
Store Transaction Output amounts as Values

### PR DESCRIPTION
**Pull request by astrojarred**
The purpose of this PR is to help make UTxO math a bit easier.
At the moment, one cannot add the amounts of `TransactionOutput`s together easily.

An example of why this might be useful is:

```python
# add outputs to a transaction with builder 

builder.outputs[0] += Value(coin=5_000_000)

# or even 
builder.outputs[0] += 5_000_000
```

The above code works only if the `outputs[0]` is already a `Value`.  If it's an `int` it won't work. The current workaround is to do something like:
```python
builder.outputs[0] = Value(coin=5_000_000) + builder.outputs[0]
```

so that the value is the class handling the addition, but it might be a bit easier from a UTxO math standpoint if amounts were always `Value`s (but could still be initialized with `int`s.

There might be a problem with one of the tests but I'm having trouble debugging it.

### CODE REVIEW

**Comment by astrojarred** [comment]
OK yeah it looks like `test_not_enough_input_amount` is not able to deserialize `Value({'coin': 5000000, 'multi_asset': {}})` for some reason. @cffls I'm guessing it might be more obvious to you than to me as to why this is failing.

**Comment by cffls** [comment]
It is not obvious to me either. 😆  Thanks for creating this PR! I will take it from here.

**Comment by cffls** [comment]
The issue was in the unit test, not the new code. The failed test assumed the amount was always an integer, which is not the case after this commit.

**Comment by astrojarred** [comment]
Makes total sense, thanks for updating me and patching it up!

**Pull request merged**
